# Generated by Django 2.2.5 on 2019-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='how',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foods',
            name='material',
            field=models.TextField(),
        ),
    ]
