# Generated by Django 2.2.5 on 2019-10-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20191028_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='time',
            field=models.CharField(default=-0.1, max_length=50),
            preserve_default=False,
        ),
    ]
