# Generated by Django 2.2.5 on 2019-10-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_foods_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='time',
        ),
    ]
