# Generated by Django 2.2.5 on 2019-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_foods_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='points',
            field=models.TextField(default=' '),
        ),
    ]
